comment: true

coverage:
  status:
    project:
      default:
        informational: true
    changes:
      default:
        informational: true
    patch:
      default:
        informational: true
